export const tabl_t100xml = `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_TABL" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DD02V>
    <TABNAME>T100</TABNAME>
    <DDLANGUAGE>E</DDLANGUAGE>
    <TABCLASS>TRANSP</TABCLASS>
    <DDTEXT>Messages</DDTEXT>
    <CONTFLAG>A</CONTFLAG>
    <EXCLASS>1</EXCLASS>
   </DD02V>
   <DD09L>
    <TABNAME>T100</TABNAME>
    <AS4LOCAL>A</AS4LOCAL>
    <TABKAT>0</TABKAT>
    <TABART>APPL0</TABART>
    <UEBERSETZ>N</UEBERSETZ>
    <BUFALLOW>N</BUFALLOW>
   </DD09L>
   <DD03P_TABLE>
    <DD03P>
     <TABNAME>T100</TABNAME>
     <FIELDNAME>SPRSL</FIELDNAME>
     <DDLANGUAGE>E</DDLANGUAGE>
     <POSITION>0001</POSITION>
     <KEYFLAG>X</KEYFLAG>
     <ADMINFIELD>0</ADMINFIELD>
     <INTTYPE>C</INTTYPE>
     <INTLEN>000002</INTLEN>
     <NOTNULL>X</NOTNULL>
     <DATATYPE>LANG</DATATYPE>
     <LENG>000001</LENG>
     <MASK>  LANG</MASK>
     <LANGUFLAG>X</LANGUFLAG>
    </DD03P>
    <DD03P>
     <TABNAME>T100</TABNAME>
     <FIELDNAME>ARBGB</FIELDNAME>
     <DDLANGUAGE>E</DDLANGUAGE>
     <POSITION>0002</POSITION>
     <KEYFLAG>X</KEYFLAG>
     <ADMINFIELD>0</ADMINFIELD>
     <INTTYPE>C</INTTYPE>
     <INTLEN>000040</INTLEN>
     <NOTNULL>X</NOTNULL>
     <DATATYPE>CHAR</DATATYPE>
     <LENG>000020</LENG>
     <MASK>  CHAR</MASK>
    </DD03P>
    <DD03P>
     <TABNAME>T100</TABNAME>
     <FIELDNAME>MSGNR</FIELDNAME>
     <DDLANGUAGE>E</DDLANGUAGE>
     <POSITION>0003</POSITION>
     <KEYFLAG>X</KEYFLAG>
     <ADMINFIELD>0</ADMINFIELD>
     <INTTYPE>C</INTTYPE>
     <INTLEN>000006</INTLEN>
     <NOTNULL>X</NOTNULL>
     <DATATYPE>CHAR</DATATYPE>
     <LENG>000003</LENG>
     <MASK>  CHAR</MASK>
    </DD03P>
    <DD03P>
     <TABNAME>T100</TABNAME>
     <FIELDNAME>TEXT</FIELDNAME>
     <DDLANGUAGE>E</DDLANGUAGE>
     <POSITION>0004</POSITION>
     <ADMINFIELD>0</ADMINFIELD>
     <INTTYPE>C</INTTYPE>
     <INTLEN>000146</INTLEN>
     <DATATYPE>CHAR</DATATYPE>
     <LENG>000073</LENG>
     <MASK>  CHAR</MASK>
    </DD03P>
   </DD03P_TABLE>
  </asx:values>
 </asx:abap>
</abapGit>`;

export const msag_zag_unit_test = `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_MSAG" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <T100A>
    <ARBGB>ZAG_UNIT_TEST</ARBGB>
    <MASTERLANG>E</MASTERLANG>
    <STEXT>test</STEXT>
   </T100A>
   <T100>
    <T100>
     <SPRSL>E</SPRSL>
     <ARBGB>ZAG_UNIT_TEST</ARBGB>
     <MSGNR>000</MSGNR>
     <TEXT>hello world</TEXT>
    </T100>
   </T100>
  </asx:values>
 </asx:abap>
</abapGit>`;

export const zag_unit_test_v = `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_VIEW" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <DD25V>
    <VIEWNAME>ZAG_UNIT_TEST_V</VIEWNAME>
    <AS4LOCAL>A</AS4LOCAL>
    <DDLANGUAGE>E</DDLANGUAGE>
    <AGGTYPE>V</AGGTYPE>
    <ROOTTAB>ZAG_UNIT_TEST_T1</ROOTTAB>
    <DDTEXT>Unit Test</DDTEXT>
    <VIEWCLASS>D</VIEWCLASS>
    <VIEWGRANT>R</VIEWGRANT>
   </DD25V>
   <DD26V_TABLE>
    <DD26V>
     <VIEWNAME>ZAG_UNIT_TEST_V</VIEWNAME>
     <TABNAME>ZAG_UNIT_TEST_T1</TABNAME>
     <TABPOS>0001</TABPOS>
     <FORTABNAME>ZAG_UNIT_TEST_T1</FORTABNAME>
    </DD26V>
    <DD26V>
     <VIEWNAME>ZAG_UNIT_TEST_V</VIEWNAME>
     <TABNAME>ZAG_UNIT_TEST_T2</TABNAME>
     <TABPOS>0002</TABPOS>
    </DD26V>
   </DD26V_TABLE>
   <DD27P_TABLE>
    <DD27P>
     <VIEWFIELD>MANDT</VIEWFIELD>
     <TABNAME>ZAG_UNIT_TEST_T1</TABNAME>
     <FIELDNAME>MANDT</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
    </DD27P>
    <DD27P>
     <VIEWFIELD>KEY_FIELD</VIEWFIELD>
     <TABNAME>ZAG_UNIT_TEST_T1</TABNAME>
     <FIELDNAME>KEY_FIELD</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
    </DD27P>
    <DD27P>
     <VIEWFIELD>DATA_FIELD</VIEWFIELD>
     <TABNAME>ZAG_UNIT_TEST_T1</TABNAME>
     <FIELDNAME>DATA_FIELD</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
     <CHECKTABLE>ZAG_UNIT_TEST_T2</CHECKTABLE>
     <SHLPORIGIN>P</SHLPORIGIN>
    </DD27P>
    <DD27P>
     <VIEWFIELD>DATA</VIEWFIELD>
     <TABNAME>ZAG_UNIT_TEST_T2</TABNAME>
     <FIELDNAME>DATA</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
     <SHLPORIGIN>F</SHLPORIGIN>
     <VALEXI>X</VALEXI>
    </DD27P>
   </DD27P_TABLE>
   <DD28J_TABLE>
    <DD28J>
     <VIEWNAME>ZAG_UNIT_TEST_V</VIEWNAME>
     <LTAB>ZAG_UNIT_TEST_T1</LTAB>
     <LFIELD>DATA_FIELD</LFIELD>
     <OPERATOR>EQ</OPERATOR>
     <RTAB>ZAG_UNIT_TEST_T2</RTAB>
     <RFIELD>KEY_FIELD</RFIELD>
     <SOURCE>S</SOURCE>
    </DD28J>
   </DD28J_TABLE>
  </asx:values>
 </asx:abap>
</abapGit>`;