// A long chain of & / && , like a SADL definition generated by SEGW (one
// string template per line). Before #1836 this transpiled to one nested
// concat( ) call per operand, see https://github.com/abaplint/transpiler/pull/1836
const CHAIN_LENGTH = 800;
const operands: string[] = [];
for (let i = 0; i < CHAIN_LENGTH; i++) {
  operands.push("|abcdefghij|");
}

export const test45 = `
DATA lv_result TYPE string.
DO 10000 TIMES.
  lv_result = ${operands.join(" && ")}.
ENDDO.`;
