import {Character} from "../types/index.js";

export * from "./abs.js";
export * from "./boolc.js";
export * from "./ceil.js";
export * from "./concat_lines_of.js";
export * from "./condense.js";
export * from "./contains.js";
export * from "./cos.js";
export * from "./count_any_of.js";
export * from "./count.js";
export * from "./escape.js";
export * from "./find.js";
export * from "./floor.js";
export * from "./frac.js";
export * from "./insert.js";
export * from "./ipow.js";
export * from "./lines.js";
export * from "./match.js";
export * from "./matches.js";
export * from "./nmax.js";
export * from "./nmin.js";
export * from "./numofchar.js";
export * from "./repeat.js";
export * from "./replace.js";
export * from "./reverse.js";
export * from "./round.js";
export * from "./segment.js";
export * from "./shift_right.js";
export * from "./shift_left.js";
export * from "./sign.js";
export * from "./sin.js";
export * from "./sqrt.js";
export * from "./strlen.js";
export * from "./substring_after.js";
export * from "./substring_before.js";
export * from "./substring.js";
export * from "./sy.js";
export * from "./tan.js";
export * from "./to_lower.js";
export * from "./to_mixed.js";
export * from "./to_upper.js";
export * from "./translate.js";
export * from "./trunc.js";
export * from "./xstrlen.js";
export const abap_true = new Character(1, {qualifiedName: "ABAP_BOOL", ddicName: "ABAP_BOOL"}).set("X").setConstant();
export const abap_false = new Character(1, {qualifiedName: "ABAP_BOOL", ddicName: "ABAP_BOOL"}).set("").setConstant();
export const abap_undefined = new Character(1, {qualifiedName: "ABAP_BOOL", ddicName: "ABAP_BOOL"}).set("-").setConstant();
export const space = new Character(1, {qualifiedName: "ABAP_BOOL", ddicName: "ABAP_BOOL"}).set(" ").setConstant();
